FROM node:16-alpine3.14

# Create app directory
WORKDIR /usr/src/

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY dist dist

EXPOSE 9000
ENTRYPOINT [ "node", "dist/main.js" ]